server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    proxy_pass /api/ {
        proxy_pass localhost:8080;
        # 백엔드 포트 입력할 예정
    }
}